os:
  - linux

language: php

php:
  - '7.3'

services:
  - postgresql

jobs:
  include:
    - stage: test
      before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
      - psql -c 'SET session_replication_role = 'replica';'
      - cd backend-api/
      - composer self-update
      - composer update
      - composer install --no-interaction
      - cp .env.travis .env
      - php artisan migrate --force
      - php artisan db:seed

      script:
        - vendor/bin/phpunit --testdox
        
    - stage: stage
      script: skip
    
