os:
  - linux

language: php

php:
  - '7.1'

services:
  - postgresql

jobs:
  include:
    - stage: test
      before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
      - psql -c 'SET session_replication_role = 'replica';'
      - cd backend-api/
      - composer self-update
      - composer install --no-interaction
      - cp .env.travis .env
      - php artisan migrate --force
      - php artisan db:seed
      - php artisan serve &

      script:
        - vendor/bin/phpunit --testdox
        # - vendor/bin/behat

      after_success:
        - cd ../
        - ./push.sh

    - stage: stage
      script: skip

