<?php

use Illuminate\Database\Seeder;
use App\DxAsociado;
class DxAsociadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dxAsociados = [
            ['letra' => 'N','entero' => -1,'decimal' => 0, 'significado' => 'Alteraciones glomerulares mínimas'],
            ['letra' => 'N','entero' => -1,'decimal' => 1, 'significado' => 'Lesiones glomerulares focales y segmentarias'],
            ['letra' => 'N','entero' => -1,'decimal' => 2, 'significado' => 'Glomerulonefritis membranosa difusa'],
            ['letra' => 'N','entero' => -1,'decimal' => 3, 'significado' => 'Glomerulonefritis proliferativa mesangial difusa'],
            ['letra' => 'N','entero' => -1,'decimal' => 4, 'significado' => 'Glomerulonefritis proliferativa endocapilar difusa'],
            ['letra' => 'N','entero' => -1,'decimal' => 5, 'significado' => 'Glomerulonefritis mesangiocapilar difusa'],
            ['letra' => 'N','entero' => -1,'decimal' => 6, 'significado' => 'Enfermedad por depósitos densos'],
            ['letra' => 'N','entero' => -1,'decimal' => 7, 'significado' => 'Glomerulonefritis difusa con semilunas'],
            ['letra' => 'N','entero' => -1,'decimal' => 8, 'significado' => 'Otras'],
            ['letra' => 'N','entero' => -1,'decimal' => 9, 'significado' => 'No especificada'],
            ['letra' => 'N','entero' => 0,'decimal' => -1, 'significado' => 'Síndrome nefrítico agudo'],
            ['letra' => 'N','entero' => 1,'decimal' => -1, 'significado' => 'Síndrome nefrítico rápidamente progresivo'],
            ['letra' => 'N','entero' => 2,'decimal' => -1, 'significado' => 'Hematuria recurrente y persistente'],
            ['letra' => 'N','entero' => 3,'decimal' => -1, 'significado' => 'Síndrome nefrítico crónico'],
            ['letra' => 'N','entero' => 4,'decimal' => -1, 'significado' => 'Síndrome nefrótico'],
            ['letra' => 'N','entero' => 5,'decimal' => -1, 'significado' => 'Síndrome nefrítico no especificado'],
            ['letra' => 'N','entero' => 6,'decimal' => -1, 'significado' => 'Proteinuria aislada con lesión morfológica especificada'],
            ['letra' => 'N','entero' => 7,'decimal' => -1, 'significado' => 'Nefropatía hereditaria, no clasificada en otra parte'],
            ['letra' => 'N','entero' => 8,'decimal' => -1, 'significado' => 'Trastornos glomerulares en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' => 8,'decimal' => 0, 'significado' => 'Trastornos glomerulares en enfermedades infecciosas y parasitarias clasificadas en otra parte'],
            ['letra' => 'N','entero' => 8,'decimal' => 1, 'significado' => 'Trastornos glomerulares en enfermedades neoplásicas'],
            ['letra' => 'N','entero' => 8,'decimal' => 2, 'significado' => 'Trastornos glomerulares en enfermedades de la sangre y otros trastornos que afectan al mecanismo inmunitario'],
            ['letra' => 'N','entero' => 8,'decimal' => 3, 'significado' => 'Trastornos glomerulares en diabetes mellitu'],
            ['letra' => 'N','entero' => 8,'decimal' => 4, 'significado' => 'Trastornos glomerulares en otras enfermedades endocrinas, nutricionales y metabólicas'],
            ['letra' => 'N','entero' => 8,'decimal' => 5, 'significado' => 'Trastornos glomerulares en trastornos sistémicos del tejido conjuntivo'],
            ['letra' => 'N','entero' => 8,'decimal' => 8, 'significado' => 'Trastornos glomerulares en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' => 10,'decimal' => -1, 'significado' => 'Nefritis tubulointersticial aguda'],
            ['letra' => 'N','entero' => 11,'decimal' => -1, 'significado' => 'Nefritis tubulointersticial crónica'],
            ['letra' => 'N','entero' => 11,'decimal' => 0, 'significado' => ' Pielonefritis crónica no obstructiva asociada a reflujo vesicoureteral'],
            ['letra' => 'N','entero' => 11,'decimal' => 1, 'significado' => 'Pielonefritis crónica obstructiva'],
            ['letra' => 'N','entero' => 11,'decimal' => 8, 'significado' => 'Otras nefritis tubulointersticiales crónicas'],
            ['letra' => 'N','entero' => 11,'decimal' => 9, 'significado' => 'Nefritis tubulointersticial crónica, sin otra especificación'],
            ['letra' => 'N','entero' => 12,'decimal' => -1, 'significado' => 'Nefritis tubulointersticial, no especificada como aguda o crónica'],
            ['letra' => 'N','entero' => 13,'decimal' => 0, 'significado' => 'Hidronefrosis con obstrucción de la unión urétero-pélvica.'],
            ['letra' => 'N','entero' => 13,'decimal' => 1, 'significado' => 'Hidronefrosis con estrechez ureteral, no clasificada en otra parte'],
            ['letra' => 'N','entero' => 13,'decimal' => 2, 'significado' => 'Hidronefrosis con obstrucción por cálculos del riñón y del uréter'],
            ['letra' => 'N','entero' => 13,'decimal' => 3, 'significado' => 'Otras hidronefrosis y no especificadas'],
            ['letra' => 'N','entero' => 13,'decimal' => 4, 'significado' => 'Hidrouréter'],
            ['letra' => 'N','entero' => 13,'decimal' => 5, 'significado' => 'Torsión y estrechez del uréter sin hidronefrosis'],
            ['letra' => 'N','entero' => 13,'decimal' => 6, 'significado' => 'Pionefrosis'],
            ['letra' => 'N','entero' => 13,'decimal' => 7, 'significado' => 'Uropatía asociada con reflujo vesicoureteral'],
            ['letra' => 'N','entero' => 13,'decimal' => 8, 'significado' => 'Otras uropatías obstructivas y por reflujo'],
            ['letra' => 'N','entero' => 13,'decimal' => 9, 'significado' => 'Uropatía obstructiva y por reflujo, sin otra especificación'],
            ['letra' => 'N','entero' => 14,'decimal' => -1, 'significado' => 'Afecciones tubulares y tubulointersticiales inducidas por drogas y por metales pesados'],
            ['letra' => 'N','entero' => 14,'decimal' => 0, 'significado' => 'Nefropatía inducida por analgésicos'],
            ['letra' => 'N','entero' => 14,'decimal' => 1, 'significado' => 'Nefropatía inducida por otras drogas, medicamentos y sustancias biológicas'],
            ['letra' => 'N','entero' => 14,'decimal' => 2, 'significado' => 'Nefropatía inducida por drogas, medicamentos y sustancias biológicas no especificadas'],
            ['letra' => 'N','entero' => 14,'decimal' => 3, 'significado' => 'Nefropatía inducida por metales pesados'],
            ['letra' => 'N','entero' => 14,'decimal' => 4, 'significado' => 'Nefropatía tóxica, no clasificada en otra parte'],
            ['letra' => 'N','entero' => 15,'decimal' => -1, 'significado' => 'Otras enfermedades renales tubulointersticiales'],
            ['letra' => 'N','entero' => 15,'decimal' => 0, 'significado' => 'Nefropatía de los Balcanes'],
            ['letra' => 'N','entero' => 15,'decimal' => 1, 'significado' => 'Absceso renal y perirrenal'],
            ['letra' => 'N','entero' => 15,'decimal' => 8, 'significado' => 'Otras enfermedades renales tubulointersticiales especificadas'],
            ['letra' => 'N','entero' => 15,'decimal' => 9, 'significado' => 'Enfermedad renal tubulointersticial, no especificada'],
            ['letra' => 'N','entero' => 16,'decimal' => -1, 'significado' => 'Trastornos renales tubulointersticiales en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' => 16,'decimal' => 0, 'significado' => 'Trastornos renales tubulointersticiales en enfermedades infecciosas y parasitarias clasificadas en otra parte'],
            ['letra' => 'N','entero' => 16,'decimal' => 1, 'significado' => 'Trastornos renales tubulointersticiales en enfermedades neoplásicas'],
            ['letra' => 'N','entero' => 16,'decimal' => 2, 'significado' => 'Trastornos renales tubulointersticiales en enfermedades de la sangre y en trastornos que afectan el mecanismo inmunitario'],
            ['letra' => 'N','entero' => 16,'decimal' => 3, 'significado' => 'Trastornos renales tubulointersticiales en enfermedades metabólicas'],
            ['letra' => 'N','entero' => 16,'decimal' => 4, 'significado' => 'Trastornos renales tubulointersticiales en enfermedades del tejido conjuntivo'],
            ['letra' => 'N','entero' => 16,'decimal' => 5, 'significado' => 'Trastornos renales tubulointersticiales en rechazo de trasplante (T86.- +)'],
            ['letra' => 'N','entero' => 16,'decimal' => 8, 'significado' => 'Trastornos renales tubulointersticiales en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' => 17,'decimal' => -1, 'significado' => 'Insuficiencia renal aguda'],
            ['letra' => 'N','entero' => 17,'decimal' => 0, 'significado' => 'Insuficiencia renal aguda con necrosis tubular'],
            ['letra' => 'N','entero' => 17,'decimal' => 1, 'significado' => 'Insuficiencia renal aguda con necrosis cortical aguda'],
            ['letra' => 'N','entero' => 17,'decimal' => 2, 'significado' => 'Insuficiencia renal aguda con necrosis medular'],
            ['letra' => 'N','entero' => 17,'decimal' => 8, 'significado' => 'Otras insuficiencias renales agudas'],
            ['letra' => 'N','entero' => 17,'decimal' => 9, 'significado' => 'Insuficiencia renal aguda, no especificada'],
            ['letra' => 'N','entero' => 18,'decimal' => -1, 'significado' => 'Insuficiencia renal crónica'],
            ['letra' => 'N','entero' => 18,'decimal' => 0, 'significado' => 'Insuficiencia renal terminal'],
            ['letra' => 'N','entero' => 18,'decimal' => 8, 'significado' => 'Otras insuficiencias renales crónicas'],
            ['letra' => 'N','entero' => 18,'decimal' => 9, 'significado' => 'Insuficiencia renal crónica, no especificada'],
            ['letra' => 'N','entero' => 19,'decimal' => -1, 'significado' => 'Insuficiencia renal no especificada'],
            ['letra' => 'N','entero' => 20,'decimal' => -1, 'significado' => 'Cálculo del riñón y del uréter'],
            ['letra' => 'N','entero' => 20,'decimal' => 0, 'significado' => 'Cálculo del riñón'],
            ['letra' => 'N','entero' => 20,'decimal' => 1, 'significado' => 'Cálculo del uréter'],
            ['letra' => 'N','entero' => 20,'decimal' => 2, 'significado' => 'Cálculo del riñón con cálculo del uréter'],
            ['letra' => 'N','entero' => 20,'decimal' => 9, 'significado' => 'Cálculo urinario, no especificado'],
            ['letra' => 'N','entero' => 21,'decimal' => -1, 'significado' => 'Cálculo de las vías urinarias inferiores'],
            ['letra' => 'N','entero' => 21,'decimal' => 0, 'significado' => 'Cálculo en la vejiga'],
            ['letra' => 'N','entero' => 21,'decimal' => 1, 'significado' => 'Cálculo en la uretra'],
            ['letra' => 'N','entero' => 21,'decimal' => 8, 'significado' => 'Otros cálculos de las vías urinarias inferiores'],
            ['letra' => 'N','entero' => 21,'decimal' => 9, 'significado' => 'Cálculo de las vías urinarias inferiores, no especificado'],
            ['letra' => 'N','entero' => 22,'decimal' => -1, 'significado' => 'Cálculo de las vías urinarias en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' => 22,'decimal' => 0, 'significado' => 'Litiasis urinaria en esquistosomiasis [bilharziasis] (B65.-+)'],
            ['letra' => 'N','entero' => 22,'decimal' => 8, 'significado' => 'Cálculo de las vías urinarias en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' => 23,'decimal' => -1, 'significado' => 'Cólico renal, no especificado'],
            ['letra' => 'N','entero' =>25,'decimal' => -1, 'significado' => ' Trastornos resultantes de la función tubular renal alterada'],
            ['letra' => 'N','entero' =>25,'decimal' => 0, 'significado' => ' Osteodistrofia renal'],
            ['letra' => 'N','entero' =>25,'decimal' => 1, 'significado' => ' Diabetes insí­pida nefrógena'],
            ['letra' => 'N','entero' =>25,'decimal' => 8, 'significado' => ' Otros trastornos resultantes de la función tubular renal alterada'],
            ['letra' => 'N','entero' =>25,'decimal' => 9, 'significado' => ' Trastorno no especificado, resultante de la función tubular renal alterada'],
            ['letra' => 'N','entero' =>26,'decimal' => -1, 'significado' => ' Riñón contraí­do, no especificado'],
            ['letra' => 'N','entero' =>27,'decimal' => -1, 'significado' => ' Riñón pequeño de causa desconocida'],
            ['letra' => 'N','entero' =>27,'decimal' => 0, 'significado' => ' Riñón pequeño, unilateral'],
            ['letra' => 'N','entero' =>27,'decimal' => 1, 'significado' => ' Riñón pequeño, bilateral'],
            ['letra' => 'N','entero' =>27,'decimal' => 9, 'significado' => ' Riñón pequeño, no especificado'],
            ['letra' => 'N','entero' =>28,'decimal' => -1, 'significado' => ' Otros trastornos del riñón y del uréter, no clasificados en otra parte'],
            ['letra' => 'N','entero' =>28,'decimal' => 0, 'significado' => ' Isquemia e infarto del riñón'],
            ['letra' => 'N','entero' =>28,'decimal' => 1, 'significado' => ' Quiste de riñón, adquirido'],
            ['letra' => 'N','entero' =>28,'decimal' => 8, 'significado' => ' Otros trastornos especificados del riñón y del uréter'],
            ['letra' => 'N','entero' =>28,'decimal' => 9, 'significado' => ' Trastorno del riñón y del uréter, no especificado'],
            ['letra' => 'N','entero' =>29,'decimal' => -1, 'significado' => ' Otros trastornos del riñón y del uréter en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>29,'decimal' => 0, 'significado' => ' S­filis renal tardí­a'],
            ['letra' => 'N','entero' =>29,'decimal' => 8, 'significado' => ' Otros trastornos del riñón y del uréter en enfermedades infecciosas y parasitarias clasificadas en otra parte'],
            ['letra' => 'N','entero' =>29,'decimal' => 9, 'significado' => ' Otros trastornos del riñón y del uréter en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>30,'decimal' => -1, 'significado' => ' Cistitis'],
            ['letra' => 'N','entero' =>30,'decimal' => 0, 'significado' => ' Cistitis aguda'],
            ['letra' => 'N','entero' =>30,'decimal' => 1, 'significado' => ' Cistitis intersticial (crónica'],
            ['letra' => 'N','entero' =>30,'decimal' => 2, 'significado' => ' Otras cistitis crónicas'],
            ['letra' => 'N','entero' =>30,'decimal' => 3, 'significado' => ' Trigonitis'],
            ['letra' => 'N','entero' =>30,'decimal' => 4, 'significado' => ' Cistitis por irradiación'],
            ['letra' => 'N','entero' =>30,'decimal' => 8, 'significado' => ' Otras cistitis'],
            ['letra' => 'N','entero' =>30,'decimal' => 9, 'significado' => ' Cistitis, no especificada'],
            ['letra' => 'N','entero' =>31,'decimal' => -1, 'significado' => ' Disfunción neuromuscular de la vejiga, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>31,'decimal' => 0, 'significado' => ' Vejiga neuropática no inhibida, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>31,'decimal' => 1, 'significado' => ' Vejiga neuropática refleja, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>31,'decimal' => 2, 'significado' => ' Vejiga neuropática flácida, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>31,'decimal' => 8, 'significado' => ' Otras disfunciones neuromusculares de la vejiga'],
            ['letra' => 'N','entero' =>31,'decimal' => 9, 'significado' => ' Disfunción neuromuscular de la vejiga, no especificada'],
            ['letra' => 'N','entero' =>32,'decimal' => -1, 'significado' => ' Otros trastornos de la vejiga'],
            ['letra' => 'N','entero' =>32,'decimal' => 0, 'significado' => ' Obstrucción de cuello de la vejiga'],
            ['letra' => 'N','entero' =>32,'decimal' => 1, 'significado' => ' Fí­stula vesicointestinal'],
            ['letra' => 'N','entero' =>32,'decimal' => 2, 'significado' => ' Fí­stula de la vejiga, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>32,'decimal' => 3, 'significado' => ' Divertí­culo de la vejiga'],
            ['letra' => 'N','entero' =>32,'decimal' => 4, 'significado' => ' Ruptura de la vejiga, no traumática'],
            ['letra' => 'N','entero' =>32,'decimal' => 8, 'significado' => ' Otros trastornos especificados de la vejiga'],
            ['letra' => 'N','entero' =>32,'decimal' => 9, 'significado' => ' Trastorno de la vejiga, no especificado'],
            ['letra' => 'N','entero' =>33,'decimal' => -1, 'significado' => ' Trastornos de la vejiga en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>33,'decimal' => 0, 'significado' => ' Cistitis tuberculosa'],
            ['letra' => 'N','entero' =>33,'decimal' => 8, 'significado' => ' Trastornos de la vejiga en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>34,'decimal' => -1, 'significado' => ' Uretritis y sí­ndrome uretral'],
            ['letra' => 'N','entero' =>34,'decimal' => 0, 'significado' => ' Absceso uretral'],
            ['letra' => 'N','entero' =>34,'decimal' => 1, 'significado' => ' Uretritis no especí­fica'],
            ['letra' => 'N','entero' =>34,'decimal' => 2, 'significado' => ' Otras uretritis'],
            ['letra' => 'N','entero' =>34,'decimal' => 3, 'significado' => ' Sí­ndrome uretral, no especificado'],
            ['letra' => 'N','entero' =>35,'decimal' => -1, 'significado' => ' Estrechez uretral'],
            ['letra' => 'N','entero' =>35,'decimal' => 0, 'significado' => ' Estrechez uretral postraumáica'],
            ['letra' => 'N','entero' =>35,'decimal' => 1, 'significado' => ' Estrechez uretral postinfección, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>35,'decimal' => 8, 'significado' => ' Otras estrecheces uretrales'],
            ['letra' => 'N','entero' =>35,'decimal' => 9, 'significado' => ' Estrechez uretral, no especificada'],
            ['letra' => 'N','entero' =>36,'decimal' => -1, 'significado' => ' Otros trastornos de la uretra'],
            ['letra' => 'N','entero' =>36,'decimal' => 0, 'significado' => ' Fí­stula de la uretra'],
            ['letra' => 'N','entero' =>36,'decimal' => 1, 'significado' => ' Divertí­culo de la uretra'],
            ['letra' => 'N','entero' =>36,'decimal' => 2, 'significado' => ' Carúncula uretral'],
            ['letra' => 'N','entero' =>36,'decimal' => 3, 'significado' => ' Prolapso de la mucosa uretral'],
            ['letra' => 'N','entero' =>36,'decimal' => 8, 'significado' => ' Otros trastornos especificados de la uretra'],
            ['letra' => 'N','entero' =>36,'decimal' => 9, 'significado' => ' Trastorno de la uretra, no especificado'],
            ['letra' => 'N','entero' =>37,'decimal' => -1, 'significado' => ' Trastornos de la uretra en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>37,'decimal' => 0, 'significado' => ' Uretritis en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>37,'decimal' => 8, 'significado' => ' Otros trastornos uretrales en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>39,'decimal' => -1, 'significado' => ' Otros trastornos del sistema urinario'],
            ['letra' => 'N','entero' =>39,'decimal' => 0, 'significado' => ' Infección de ví­as urinarias, sitio no especificado'],
            ['letra' => 'N','entero' =>39,'decimal' => 1, 'significado' => ' Proteinuria persistente, no especificada'],
            ['letra' => 'N','entero' =>39,'decimal' => 2, 'significado' => ' Proteinuria ortostática, no especificada'],
            ['letra' => 'N','entero' =>39,'decimal' => 3, 'significado' => ' Incontinencia urinaria por tensión'],
            ['letra' => 'N','entero' =>39,'decimal' => 4, 'significado' => ' Otras incontinencias urinarias especificadas'],
            ['letra' => 'N','entero' =>39,'decimal' => 8, 'significado' => ' Otros trastornos especificados del sistema urinario'],
            ['letra' => 'N','entero' =>39,'decimal' => 9, 'significado' => ' Trastorno del sistema urinario, no especificado'],
            ['letra' => 'N','entero' =>40,'decimal' => -1, 'significado' => ' Hiperplasia de la próstata'],
            ['letra' => 'N','entero' =>41,'decimal' => -1, 'significado' => ' Enfermedades inflamatorias de la próstata'],
            ['letra' => 'N','entero' =>41,'decimal' => 0, 'significado' => ' Prostatitis aguda'],
            ['letra' => 'N','entero' =>41,'decimal' => 1, 'significado' => ' Prostatitis crónica'],
            ['letra' => 'N','entero' =>41,'decimal' => 2, 'significado' => ' Absceso de la próstata'],
            ['letra' => 'N','entero' =>41,'decimal' => 3, 'significado' => ' Prostatocistitis'],
            ['letra' => 'N','entero' =>41,'decimal' => 8, 'significado' => ' Otras enfermedades inflamatorias de la próstata'],
            ['letra' => 'N','entero' =>41,'decimal' => 9, 'significado' => ' Enfermedad inflamatoria de la próstata, no especificada'],
            ['letra' => 'N','entero' =>42,'decimal' => -1, 'significado' => ' Otros trastornos de la próstata'],
            ['letra' => 'N','entero' =>42,'decimal' => 0, 'significado' => ' Cálculo de la próstata'],
            ['letra' => 'N','entero' =>42,'decimal' => 1, 'significado' => ' Congestión y hemorragia de la próstata'],
            ['letra' => 'N','entero' =>42,'decimal' => 2, 'significado' => ' Atrofia de la próstata'],
            ['letra' => 'N','entero' =>42,'decimal' => 8, 'significado' => ' Otros trastornos especificados de la próstata'],
            ['letra' => 'N','entero' =>42,'decimal' => 9, 'significado' => ' Trastorno de la próstata, no especificado'],
            ['letra' => 'N','entero' =>43,'decimal' => -1, 'significado' => ' Hidrocele y espermatocele'],
            ['letra' => 'N','entero' =>43,'decimal' => 0, 'significado' => ' Hidrocele enquistado'],
            ['letra' => 'N','entero' =>43,'decimal' => 1, 'significado' => ' Hidrocele infectado'],
            ['letra' => 'N','entero' =>43,'decimal' => 2, 'significado' => ' Otros hidroceles'],
            ['letra' => 'N','entero' =>43,'decimal' => 3, 'significado' => ' Hidrocele, no especificado'],
            ['letra' => 'N','entero' =>43,'decimal' => 4, 'significado' => ' Espermatocele'],
            ['letra' => 'N','entero' =>44,'decimal' => -1, 'significado' => ' Torsión del testí­culo'],
            ['letra' => 'N','entero' =>45,'decimal' => -1, 'significado' => ' Orquitis y epididimitis'],
            ['letra' => 'N','entero' =>45,'decimal' => 0, 'significado' => ' Orquitis, epididimitis y orquiepididimitis con absceso'],
            ['letra' => 'N','entero' =>45,'decimal' => 9, 'significado' => ' Orquitis, epididimitis y orquiepididimitis sin absceso'],
            ['letra' => 'N','entero' =>46,'decimal' => -1, 'significado' => ' Esterilidad en el varón'],
            ['letra' => 'N','entero' =>47,'decimal' => -1, 'significado' => ' Prepucio redundante, fimosis y parafimosis'],
            ['letra' => 'N','entero' =>48,'decimal' => -1, 'significado' => ' Otros trastornos del pene'],
            ['letra' => 'N','entero' =>48,'decimal' => 0, 'significado' => ' Leucoplasia del pene'],
            ['letra' => 'N','entero' =>48,'decimal' => 1, 'significado' => ' Balanopostitis'],
            ['letra' => 'N','entero' =>48,'decimal' => 2, 'significado' => ' Otros trastornos inflamatorios del pene'],
            ['letra' => 'N','entero' =>48,'decimal' => 3, 'significado' => ' Priapismo'],
            ['letra' => 'N','entero' =>48,'decimal' => 4, 'significado' => ' Impotencia de origen orgánico'],
            ['letra' => 'N','entero' =>48,'decimal' => 5, 'significado' => ' Ulcera del pene'],
            ['letra' => 'N','entero' =>48,'decimal' => 6, 'significado' => ' Balanitis xerótica obliterante'],
            ['letra' => 'N','entero' =>48,'decimal' => 8, 'significado' => ' Otros trastornos especificados del pene'],
            ['letra' => 'N','entero' =>48,'decimal' => 9, 'significado' => ' Trastorno del pene, no especificado'],
            ['letra' => 'N','entero' =>49,'decimal' => -1, 'significado' => ' Trastornos inflamatorios de órganos genitales masculinos, no clasificados en otra parte'],
            ['letra' => 'N','entero' =>49,'decimal' => 0, 'significado' => ' Trastornos inflamatorios de vesí­cula seminal'],
            ['letra' => 'N','entero' =>49,'decimal' => 1, 'significado' => ' Trastornos inflamatorios del cordón espermático, túnica vaginal y conducto deferente'],
            ['letra' => 'N','entero' =>49,'decimal' => 2, 'significado' => ' Trastornos inflamatorios del escroto'],
            ['letra' => 'N','entero' =>49,'decimal' => 3, 'significado' => ' Otros trastornos inflamatorios de los órganos genitales masculinos'],
            ['letra' => 'N','entero' =>49,'decimal' => 9, 'significado' => ' Trastorno inflamatorio de órgano genital masculino, no especificado'],
            ['letra' => 'N','entero' =>50,'decimal' => -1, 'significado' => ' Otros trastornos de los órganos genitales masculinos'],
            ['letra' => 'N','entero' =>50,'decimal' => 0, 'significado' => ' Atrofia del testí­culo'],
            ['letra' => 'N','entero' =>50,'decimal' => 1, 'significado' => ' Trastornos vasculares de los órganos genitales masculinos'],
            ['letra' => 'N','entero' =>50,'decimal' => 8, 'significado' => ' Otros trastornos especificados de los órganos genitales masculinos'],
            ['letra' => 'N','entero' =>50,'decimal' => 9, 'significado' => ' Trastorno no especificado de los órganos genitales masculinos'],
            ['letra' => 'N','entero' =>51,'decimal' => -1, 'significado' => ' Trastornos de los órganos genitales masculinos en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>51,'decimal' => 0, 'significado' => ' Trastornos de próstata en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>51,'decimal' => 1, 'significado' => ' Trastornos del testí­culo y del epidí­dimo en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>51,'decimal' => 2, 'significado' => ' Balanitis en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>51,'decimal' => 8, 'significado' => ' Otros trastornos de los órganos genitales masculinos en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>60,'decimal' => -1, 'significado' => ' Displasia mamaria benigna'],
            ['letra' => 'N','entero' =>60,'decimal' => 0, 'significado' => ' Quiste solitario de la mama'],
            ['letra' => 'N','entero' =>60,'decimal' => 1, 'significado' => ' Mastopatí­a quí­stica difusa'],
            ['letra' => 'N','entero' =>60,'decimal' => 2, 'significado' => ' Fibroadenosis de mama'],
            ['letra' => 'N','entero' =>60,'decimal' => 3, 'significado' => ' Fibroesclerosis de mama'],
            ['letra' => 'N','entero' =>60,'decimal' => 4, 'significado' => ' Ectasia de conducto mamario'],
            ['letra' => 'N','entero' =>60,'decimal' => 8, 'significado' => ' Otras displasias mamarias benignas'],
            ['letra' => 'N','entero' =>60,'decimal' => 9, 'significado' => ' Displasia mamaria benigna, sin otra especificación'],
            ['letra' => 'N','entero' =>61,'decimal' => -1, 'significado' => ' Trastornos inflamatorios de la mama'],
            ['letra' => 'N','entero' =>62,'decimal' => -1, 'significado' => ' Hipertrofia de la mama'],
            ['letra' => 'N','entero' =>63,'decimal' => -1, 'significado' => ' Masa no especificada en la mama'],
            ['letra' => 'N','entero' =>64,'decimal' => -1, 'significado' => ' Otros trastornos de la mama'],
            ['letra' => 'N','entero' =>64,'decimal' => 0, 'significado' => ' Fisura y fí­stula del pezón'],
            ['letra' => 'N','entero' =>64,'decimal' => 1, 'significado' => ' Necrosis grasa de la mama'],
            ['letra' => 'N','entero' =>64,'decimal' => 2, 'significado' => ' Atrofia de la mama'],
            ['letra' => 'N','entero' =>64,'decimal' => 3, 'significado' => ' Galactorrea no asociada con el parto'],
            ['letra' => 'N','entero' =>64,'decimal' => 4, 'significado' => ' Mastodinia'],
            ['letra' => 'N','entero' =>64,'decimal' => 5, 'significado' => ' Otros signos y sí­ntomas relativos a la mama'],
            ['letra' => 'N','entero' =>64,'decimal' => 8, 'significado' => ' Otros trastornos especificados de la mama'],
            ['letra' => 'N','entero' =>64,'decimal' => 9, 'significado' => ' Trastorno de la mama, no especificado'],
            ['letra' => 'N','entero' =>70,'decimal' => -1, 'significado' => ' Salpingitis y ooforitis'],
            ['letra' => 'N','entero' =>70,'decimal' => 0, 'significado' => ' Salpingitis y ooforitis aguda'],
            ['letra' => 'N','entero' =>70,'decimal' => 1, 'significado' => ' Salpingitis y ooforitis crónica'],
            ['letra' => 'N','entero' =>70,'decimal' => 9, 'significado' => ' Salpingitis y ooforitis, no especificadas'],
            ['letra' => 'N','entero' =>71,'decimal' => -1, 'significado' => ' Enfermedad inflamatoria del útero, excepto del cuello uterino'],
            ['letra' => 'N','entero' =>71,'decimal' => 0, 'significado' => ' Enfermedad inflamatoria aguda del útero'],
            ['letra' => 'N','entero' =>71,'decimal' => 1, 'significado' => ' Enfermedad inflamatoria crónica del útero'],
            ['letra' => 'N','entero' =>71,'decimal' => 9, 'significado' => ' Enfermedad inflamatoria del útero, no especificada'],
            ['letra' => 'N','entero' =>72,'decimal' => -1, 'significado' => ' Enfermedad inflamatoria del cuello uterino'],
            ['letra' => 'N','entero' =>73,'decimal' => -1, 'significado' => ' Otras enfermedades pélvicas inflamatorias femeninas'],
            ['letra' => 'N','entero' =>73,'decimal' => 0, 'significado' => ' Parametritis y celulitis pélvica aguda'],
            ['letra' => 'N','entero' =>73,'decimal' => 1, 'significado' => ' Parametritis y celulitis pélvica crónica'],
            ['letra' => 'N','entero' =>73,'decimal' => 2, 'significado' => ' Parametritis y celulitis pélvica no especificada'],
            ['letra' => 'N','entero' =>73,'decimal' => 3, 'significado' => ' Peritonitis pélvica aguda, femenina'],
            ['letra' => 'N','entero' =>73,'decimal' => 4, 'significado' => ' Peritonitis pélvica crónica, femenina'],
            ['letra' => 'N','entero' =>73,'decimal' => 5, 'significado' => ' Peritonitis pélvica femenina, no especificada'],
            ['letra' => 'N','entero' =>73,'decimal' => 6, 'significado' => ' Adherencias peritoneales pélvicas femeninas'],
            ['letra' => 'N','entero' =>73,'decimal' => 8, 'significado' => ' Otras enfermedades inflamatorias pélvicas femeninas'],
            ['letra' => 'N','entero' =>73,'decimal' => 9, 'significado' => ' Enfermedad inflamatoria pélvica femenina, no especificada'],
            ['letra' => 'N','entero' =>74,'decimal' => -1, 'significado' => ' Trastornos inflamatorios de la pelvis femenina en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>74,'decimal' => 0, 'significado' => ' Infección tuberculosa del cuello del útero (A18.1+'],
            ['letra' => 'N','entero' =>74,'decimal' => 1, 'significado' => ' Enfermedad inflamatoria pélvica femenina por tuberculosis (A18.1+'],
            ['letra' => 'N','entero' =>74,'decimal' => 2, 'significado' => ' Enfermedad inflamatoria pélvica femenina por sí­filis (A51.4+, A52.7+'],
            ['letra' => 'N','entero' =>74,'decimal' => 3, 'significado' => ' Enfermedad inflamatoria pélvica femenina por gonococos (A54.2+'],
            ['letra' => 'N','entero' =>74,'decimal' => 4, 'significado' => ' Enfermedad inflamatoria pélvica femenina por clamidias (A56.1+'],
            ['letra' => 'N','entero' =>74,'decimal' => 8, 'significado' => ' Trastornos inflamatorios pélvicos femeninos en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>75,'decimal' => -1, 'significado' => ' Enfermedades de la glándula de Bartholin'],
            ['letra' => 'N','entero' =>75,'decimal' => 0, 'significado' => ' Quiste de la glándula de Bartholin'],
            ['letra' => 'N','entero' =>75,'decimal' => 1, 'significado' => ' Absceso de la glándula de Bartholin'],
            ['letra' => 'N','entero' =>75,'decimal' => 8, 'significado' => ' Otras enfermedades de la glándula de Bartholin'],
            ['letra' => 'N','entero' =>75,'decimal' => 9, 'significado' => ' Enfermedad de la glándula de Bartholin, no especificada'],
            ['letra' => 'N','entero' =>76,'decimal' => -1, 'significado' => ' Otras afecciones inflamatorias de la vagina y de la vulva'],
            ['letra' => 'N','entero' =>76,'decimal' => 0, 'significado' => ' Vaginitis aguda'],
            ['letra' => 'N','entero' =>76,'decimal' => 1, 'significado' => ' Vaginitis subaguda y crónica'],
            ['letra' => 'N','entero' =>76,'decimal' => 2, 'significado' => ' Vulvitis aguda'],
            ['letra' => 'N','entero' =>76,'decimal' => 3, 'significado' => ' Vulvitis subaguda y crónica'],
            ['letra' => 'N','entero' =>76,'decimal' => 4, 'significado' => ' Absceso vulvar'],
            ['letra' => 'N','entero' =>76,'decimal' => 5, 'significado' => ' Ulceración de la vagina'],
            ['letra' => 'N','entero' =>76,'decimal' => 6, 'significado' => ' Ulceración de la vulva'],
            ['letra' => 'N','entero' =>76,'decimal' => 8, 'significado' => ' Otras inflamaciones especificadas de la vagina y de la vulva'],
            ['letra' => 'N','entero' =>77,'decimal' => -1, 'significado' => ' Ulceración e inflamación vulvovaginal en enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>77,'decimal' => 0, 'significado' => ' Ulceración de la vulva en enfermedades infecciosas y parasitarias clasificadas en otra parte'],
            ['letra' => 'N','entero' =>77,'decimal' => 1, 'significado' => ' Vaginitis, vulvitis y vulvovaginitis en enfermedades infecciosas y parasitarias clasificadas en otra parte'],
            ['letra' => 'N','entero' =>77,'decimal' => 8, 'significado' => ' Ulceración e inflamación vulvovaginal en otras enfermedades clasificadas en otra parte'],
            ['letra' => 'N','entero' =>80,'decimal' => -1, 'significado' => ' Endometriosis'],
            ['letra' => 'N','entero' =>80,'decimal' => 0, 'significado' => ' Endometriosis del útero'],
            ['letra' => 'N','entero' =>80,'decimal' => 1, 'significado' => ' Endometriosis del ovario'],
            ['letra' => 'N','entero' =>80,'decimal' => 2, 'significado' => ' Endometriosis de la tuba uterina'],
            ['letra' => 'N','entero' =>80,'decimal' => 3, 'significado' => ' Endometriosis del peritoneo pélvico'],
            ['letra' => 'N','entero' =>80,'decimal' => 4, 'significado' => ' Endometriosis del tabique rectovaginal y de la vagina'],
            ['letra' => 'N','entero' =>80,'decimal' => 5, 'significado' => ' Endometriosis del intestino'],
            ['letra' => 'N','entero' =>80,'decimal' => 6, 'significado' => ' Endometriosis en cicatriz cutánea'],
            ['letra' => 'N','entero' =>80,'decimal' => 8, 'significado' => ' Otras endometriosis'],
            ['letra' => 'N','entero' =>80,'decimal' => 9, 'significado' => ' Endometriosis, no especificada'],
            ['letra' => 'N','entero' =>81,'decimal' => -1, 'significado' => ' Prolapso genital femenino'],
            ['letra' => 'N','entero' =>81,'decimal' => 0, 'significado' => ' Uretrocele femenino'],
            ['letra' => 'N','entero' =>81,'decimal' => 1, 'significado' => ' Cistocele'],
            ['letra' => 'N','entero' =>81,'decimal' => 2, 'significado' => ' Prolapso uterovaginal incompleto'],
            ['letra' => 'N','entero' =>81,'decimal' => 3, 'significado' => ' Prolapso uterovaginal completo'],
            ['letra' => 'N','entero' =>81,'decimal' => 4, 'significado' => ' Prolapso uterovaginal, sin otra especificación'],
            ['letra' => 'N','entero' =>81,'decimal' => 5, 'significado' => ' Enterocele vaginal'],
            ['letra' => 'N','entero' =>81,'decimal' => 6, 'significado' => ' Rectocele'],
            ['letra' => 'N','entero' =>81,'decimal' => 8, 'significado' => ' Otros prolapsos genitales femeninos'],
            ['letra' => 'N','entero' =>81,'decimal' => 9, 'significado' => ' Prolapso genital femenino, no especificado'],
            ['letra' => 'N','entero' =>82,'decimal' => -1, 'significado' => ' Fí­stulas que afectan el tracto genital femenino'],
            ['letra' => 'N','entero' =>82,'decimal' => 0, 'significado' => ' Fí­stula vesicovaginal'],
            ['letra' => 'N','entero' =>82,'decimal' => 1, 'significado' => ' Otras fí­stulas de las ví­as genitourinarias femeninas'],
            ['letra' => 'N','entero' =>82,'decimal' => 2, 'significado' => ' Fí­stula de la vagina al intestino delgado'],
            ['letra' => 'N','entero' =>82,'decimal' => 3, 'significado' => ' Fí­stula de la vagina al intestino grueso'],
            ['letra' => 'N','entero' =>82,'decimal' => 4, 'significado' => ' Otras fí­stulas del tracto genital femenino al tracto intestinal'],
            ['letra' => 'N','entero' =>82,'decimal' => 5, 'significado' => ' Fí­stula del tracto genital femenino a la piel'],
            ['letra' => 'N','entero' =>82,'decimal' => 8, 'significado' => ' Otras fí­stulas del tracto genital femenino'],
            ['letra' => 'N','entero' =>82,'decimal' => 9, 'significado' => ' Fí­stula del tracto genital femenino, sin otra especificación'],
            ['letra' => 'N','entero' =>83,'decimal' => -1, 'significado' => ' Trastornos no inflamatorios del ovario, de la trompa de Falopio y del ligamento ancho'],
            ['letra' => 'N','entero' =>83,'decimal' => 0, 'significado' => ' Quiste folicular del ovario'],
            ['letra' => 'N','entero' =>83,'decimal' => 1, 'significado' => ' Quiste del cuerpo amarillo'],
            ['letra' => 'N','entero' =>83,'decimal' => 2, 'significado' => ' Otros quistes ováricos y los no especificados'],
            ['letra' => 'N','entero' =>83,'decimal' => 3, 'significado' => ' Atrofia adquirida del ovario y de la trompa de Falopio'],
            ['letra' => 'N','entero' =>83,'decimal' => 4, 'significado' => ' Prolapso y hernia del ovario y de la trompa de Falopio'],
            ['letra' => 'N','entero' =>83,'decimal' => 5, 'significado' => ' Torsión de ovario, pedí­culo de ovario y trompa de Falopio'],
            ['letra' => 'N','entero' =>83,'decimal' => 6, 'significado' => ' Hematosalpinx'],
            ['letra' => 'N','entero' =>83,'decimal' => 7, 'significado' => ' Hematoma del ligamento ancho'],
            ['letra' => 'N','entero' =>83,'decimal' => 8, 'significado' => ' Otros trastornos no inflamatorios del ovario, de la trompa de Falopio y del ligamento ancho'],
            ['letra' => 'N','entero' =>83,'decimal' => 9, 'significado' => ' Enfermedad no inflamatoria del ovario, de la trompa de Falopio y del ligamento ancho, no especificada'],
            ['letra' => 'N','entero' =>84,'decimal' => -1, 'significado' => ' Pólipo del tracto genital femenino'],
            ['letra' => 'N','entero' =>84,'decimal' => 0, 'significado' => ' Pólipo del cuerpo del útero'],
            ['letra' => 'N','entero' =>84,'decimal' => 1, 'significado' => ' Pólipo del cuello del útero'],
            ['letra' => 'N','entero' =>84,'decimal' => 2, 'significado' => ' Pólipo de la vagina'],
            ['letra' => 'N','entero' =>84,'decimal' => 3, 'significado' => ' Pólipo de la vulva'],
            ['letra' => 'N','entero' =>84,'decimal' => 8, 'significado' => ' Pólipos de otras partes del tracto genital femenino'],
            ['letra' => 'N','entero' =>84,'decimal' => 9, 'significado' => ' Pólipo del tracto genital femenino, no especificado'],
            ['letra' => 'N','entero' =>85,'decimal' => -1, 'significado' => ' Otros trastornos no inflamatorios del útero, excepto del cuello'],
            ['letra' => 'N','entero' =>85,'decimal' => 0, 'significado' => ' Hiperplasia de glándula del endometrio:'],
            ['letra' => 'N','entero' =>85,'decimal' => 1, 'significado' => ' Hiperplasia adenomatosa del endometrio'],
            ['letra' => 'N','entero' =>85,'decimal' => 2, 'significado' => ' Hipertrofia del útero'],
            ['letra' => 'N','entero' =>85,'decimal' => 3, 'significado' => ' Subinvolución del útero'],
            ['letra' => 'N','entero' =>85,'decimal' => 4, 'significado' => ' Mala posición del útero'],
            ['letra' => 'N','entero' =>85,'decimal' => 5, 'significado' => ' Inversión del útero'],
            ['letra' => 'N','entero' =>85,'decimal' => 6, 'significado' => ' Sinequias intrauterinas'],
            ['letra' => 'N','entero' =>85,'decimal' => 7, 'significado' => ' Hematómetra'],
            ['letra' => 'N','entero' =>85,'decimal' => 8, 'significado' => ' Otros trastornos no inflamatorios especificados del útero'],
            ['letra' => 'N','entero' =>85,'decimal' => 9, 'significado' => ' Trastorno no inflamatorio del útero, no especificado'],
            ['letra' => 'N','entero' =>86,'decimal' => -1, 'significado' => ' Erosión y ectropión del cuello del útero'],
            ['letra' => 'N','entero' =>87,'decimal' => -1, 'significado' => ' Displasia del cuello uterino'],
            ['letra' => 'N','entero' =>87,'decimal' => 0, 'significado' => ' Displasia cervical leve'],
            ['letra' => 'N','entero' =>87,'decimal' => 1, 'significado' => ' Displasia cervical moderada'],
            ['letra' => 'N','entero' =>87,'decimal' => 2, 'significado' => ' Displasia cervical severa, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>87,'decimal' => 9, 'significado' => ' Displasia del cuello del útero, no especificada'],
            ['letra' => 'N','entero' =>88,'decimal' => -1, 'significado' => ' Otros trastornos no inflamatorios del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 0, 'significado' => ' Leucoplasia del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 1, 'significado' => ' Laceración antigua del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 2, 'significado' => ' Estrechez y estenosis del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 3, 'significado' => ' Incompetencia del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 4, 'significado' => ' Elongación hipertrófica del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 8, 'significado' => ' Otros trastornos no inflamatorios especificados del cuello del útero'],
            ['letra' => 'N','entero' =>88,'decimal' => 9, 'significado' => ' Trastorno no inflamatorio del cuello del útero, no especificado'],
            ['letra' => 'N','entero' =>89,'decimal' => -1, 'significado' => ' Otros trastornos no inflamatorios de la vagina'],
            ['letra' => 'N','entero' =>89,'decimal' => 0, 'significado' => ' Displasia vaginal leve'],
            ['letra' => 'N','entero' =>89,'decimal' => 1, 'significado' => ' Displasia vaginal moderada'],
            ['letra' => 'N','entero' =>89,'decimal' => 2, 'significado' => ' Displasia vaginal severa, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>89,'decimal' => 3, 'significado' => ' Displasia de la vagina, no especificada'],
            ['letra' => 'N','entero' =>89,'decimal' => 4, 'significado' => ' Leucoplasia de la vagina'],
            ['letra' => 'N','entero' =>89,'decimal' => 5, 'significado' => ' Estrechez y atresia de la vagina'],
            ['letra' => 'N','entero' =>89,'decimal' => 6, 'significado' => ' Anillo de himen estrecho'],
            ['letra' => 'N','entero' =>89,'decimal' => 7, 'significado' => ' Hematocolpos'],
            ['letra' => 'N','entero' =>89,'decimal' => 8, 'significado' => ' Otros trastornos especificados no inflamatorios de la vagina'],
            ['letra' => 'N','entero' =>89,'decimal' => 9, 'significado' => ' Trastorno no inflamatorio de la vagina, no especificado'],
            ['letra' => 'N','entero' =>90,'decimal' => -1, 'significado' => ' Otros trastornos no inflamatorios de la vulva y del perineo'],
            ['letra' => 'N','entero' =>90,'decimal' => 0, 'significado' => ' Displasia vulvar leve'],
            ['letra' => 'N','entero' =>90,'decimal' => 1, 'significado' => ' Displasia vulvar moderada'],
            ['letra' => 'N','entero' =>90,'decimal' => 2, 'significado' => ' Displasia vulvar severa, no clasificada en otra parte'],
            ['letra' => 'N','entero' =>90,'decimal' => 3, 'significado' => ' Displasia de la vulva, no especificada'],
            ['letra' => 'N','entero' =>90,'decimal' => 4, 'significado' => ' Leucoplasia de la vulva'],
            ['letra' => 'N','entero' =>90,'decimal' => 5, 'significado' => ' Atrofia de la vulva'],
            ['letra' => 'N','entero' =>90,'decimal' => 6, 'significado' => ' Hipertrofia de la vulva'],
            ['letra' => 'N','entero' =>90,'decimal' => 7, 'significado' => ' Quiste de la vulva'],
            ['letra' => 'N','entero' =>90,'decimal' => 8, 'significado' => ' Otros trastornos no inflamatorios especificados de la vulva y del perineo'],
            ['letra' => 'N','entero' =>90,'decimal' => 9, 'significado' => ' Trastorno no inflamatorio de la vulva y del perineo, no especificado'],
            ['letra' => 'N','entero' =>91,'decimal' => -1, 'significado' => ' Menstruación ausente, escasa o rara'],
            ['letra' => 'N','entero' =>91,'decimal' => 0, 'significado' => ' Amenorrea primaria'],
            ['letra' => 'N','entero' =>91,'decimal' => 1, 'significado' => ' Amenorrea secundaria'],
            ['letra' => 'N','entero' =>91,'decimal' => 2, 'significado' => ' Amenorrea, sin otra especificación'],
            ['letra' => 'N','entero' =>91,'decimal' => 3, 'significado' => ' Oligomenorrea primaria'],
            ['letra' => 'N','entero' =>91,'decimal' => 4, 'significado' => ' Oligomenorrea secundaria'],
            ['letra' => 'N','entero' =>91,'decimal' => 5, 'significado' => ' Oligomenorrea, no especificada'],
            ['letra' => 'N','entero' =>92,'decimal' => -1, 'significado' => ' Menstruación excesiva, frecuente e irregular'],
            ['letra' => 'N','entero' =>92,'decimal' => 0, 'significado' => ' Menstruación excesiva y frecuente con ciclo regular'],
            ['letra' => 'N','entero' =>92,'decimal' => 1, 'significado' => ' Menstruación excesiva y frecuente con ciclo irregular'],
            ['letra' => 'N','entero' =>92,'decimal' => 2, 'significado' => ' Menstruación excesiva en la pubertad'],
            ['letra' => 'N','entero' =>92,'decimal' => 3, 'significado' => ' Hemorragia por ovulación'],
            ['letra' => 'N','entero' =>92,'decimal' => 4, 'significado' => ' Hemorragia excesiva en perí­odo premenopáusico'],
            ['letra' => 'N','entero' =>92,'decimal' => 5, 'significado' => ' Otras menstruaciones irregulares especificadas'],
            ['letra' => 'N','entero' =>92,'decimal' => 6, 'significado' => ' Menstruación irregular, no especificada'],
            ['letra' => 'N','entero' =>93,'decimal' => -1, 'significado' => ' Otras hemorragias uterinas o vaginales anormales'],
            ['letra' => 'N','entero' =>93,'decimal' => 0, 'significado' => ' Hemorragia postcoito y postcontacto'],
            ['letra' => 'N','entero' =>93,'decimal' => 8, 'significado' => ' Otras hemorragias uterinas o vaginales anormales especificadas'],
            ['letra' => 'N','entero' =>93,'decimal' => 9, 'significado' => ' Hemorragia vaginal y uterina anormal, no especificada'],
            ['letra' => 'N','entero' =>94,'decimal' => -1, 'significado' => ' Dolor y otras afecciones relacionadas con los órganos genitales femeninos y con el ciclo menstrual'],
            ['letra' => 'N','entero' =>94,'decimal' => 0, 'significado' => ' Dolor intermenstrual'],
            ['letra' => 'N','entero' =>94,'decimal' => 1, 'significado' => ' Dispareunia'],
            ['letra' => 'N','entero' =>94,'decimal' => 2, 'significado' => ' Vaginismo'],
            ['letra' => 'N','entero' =>94,'decimal' => 3, 'significado' => ' Sí­ndrome de tensión premenstrual'],
            ['letra' => 'N','entero' =>94,'decimal' => 4, 'significado' => ' Dismenorrea primaria'],
            ['letra' => 'N','entero' =>94,'decimal' => 5, 'significado' => ' Dismenorrea secundaria'],
            ['letra' => 'N','entero' =>94,'decimal' => 6, 'significado' => ' Dismenorrea, no especificada'],
            ['letra' => 'N','entero' =>94,'decimal' => 8, 'significado' => ' Otras afecciones especificadas asociadas con los órganos genitales femeninos y el ciclo menstrual'],
            ['letra' => 'N','entero' =>94,'decimal' => 9, 'significado' => ' Afecciones no especificadas asociadas con los órganos genitales femeninos y el ciclo menstrual'],
            ['letra' => 'N','entero' =>95,'decimal' => -1, 'significado' => ' Otros trastornos menopáusicos y perimenopáusicos'],
            ['letra' => 'N','entero' =>95,'decimal' => 0, 'significado' => ' Hemorragia postmenopáusica'],
            ['letra' => 'N','entero' =>95,'decimal' => 1, 'significado' => ' Estados menopáusicos y climatéricos femeninos'],
            ['letra' => 'N','entero' =>95,'decimal' => 2, 'significado' => ' Vaginitis atrófica postmenopáusica'],
            ['letra' => 'N','entero' =>95,'decimal' => 3, 'significado' => ' Estados asociados con menopausia artificial'],
            ['letra' => 'N','entero' =>95,'decimal' => 8, 'significado' => ' Otros trastornos menopáusicos y perimenopáusicos especificados'],
            ['letra' => 'N','entero' =>95,'decimal' => 9, 'significado' => ' Trastorno menopáusico y perimenopáusico, no especificado'],
            ['letra' => 'N','entero' =>96,'decimal' => -1, 'significado' => ' Abortadora habitual'],
            ['letra' => 'N','entero' =>97,'decimal' => -1, 'significado' => ' Infertilidad femenina'],
            ['letra' => 'N','entero' =>97,'decimal' => 0, 'significado' => ' Infertilidad femenina asociada con falta de ovulación'],
            ['letra' => 'N','entero' =>97,'decimal' => 1, 'significado' => ' Infertilidad femenina de origen tubárico'],
            ['letra' => 'N','entero' =>97,'decimal' => 2, 'significado' => ' Infertilidad femenina de origen uterino'],
            ['letra' => 'N','entero' =>97,'decimal' => 3, 'significado' => ' Infertilidad femenina de origen cervical'],
            ['letra' => 'N','entero' =>97,'decimal' => 4, 'significado' => ' Infertilidad femenina asociada con factores masculinos'],
            ['letra' => 'N','entero' =>97,'decimal' => 8, 'significado' => ' Infertilidad femenina de otro origen'],
            ['letra' => 'N','entero' =>97,'decimal' => 9, 'significado' => ' Infertilidad femenina, no especificada'],
            ['letra' => 'N','entero' =>98,'decimal' => -1, 'significado' => ' Complicaciones asociadas con la fecundación artificial'],
            ['letra' => 'N','entero' =>98,'decimal' => 0, 'significado' => ' Infección asociada con inseminación artificial'],
            ['letra' => 'N','entero' =>98,'decimal' => 1, 'significado' => ' Hiperestimulación de ovarios'],
            ['letra' => 'N','entero' =>98,'decimal' => 2, 'significado' => ' Complicaciones en el intento de introducción del huevo fecundado en la fertilización in vitro'],
            ['letra' => 'N','entero' =>98,'decimal' => 3, 'significado' => ' Complicaciones en el intento de introducción del embrión en la transferencia de embriones'],
            ['letra' => 'N','entero' =>98,'decimal' => 8, 'significado' => ' Otras complicaciones asociadas con la fecundación artificial'],
            ['letra' => 'N','entero' =>98,'decimal' => 9, 'significado' => ' Complicación no especificada asociada con la fecundación artificial'],
            ['letra' => 'N','entero' =>99,'decimal' => -1, 'significado' => ' Trastornos del sistema genitourinario consecutivos a procedimientos, no clasificados en otra parte'],
            ['letra' => 'N','entero' =>99,'decimal' => 0, 'significado' => ' Insuficiencia renal consecutiva a procedimientos'],
            ['letra' => 'N','entero' =>99,'decimal' => 1, 'significado' => ' Estrechez uretral consecutiva a procedimientos'],
            ['letra' => 'N','entero' =>99,'decimal' => 2, 'significado' => ' Adherencias postoperatorias de la vagina'],
            ['letra' => 'N','entero' =>99,'decimal' => 3, 'significado' => ' Prolapso de la cúpula vaginal después de histerectomí­a'],
            ['letra' => 'N','entero' =>99,'decimal' => 4, 'significado' => ' Adherencias peritoneales pélvicas consecutivas a procedimientos'],
            ['letra' => 'N','entero' =>99,'decimal' => 5, 'significado' => ' Mal funcionamiento de estoma externo de ví­as urinarias'],
            ['letra' => 'N','entero' =>99,'decimal' => 8, 'significado' => ' Otros trastornos del sistema genitourinario consecutivos a procedimientos'],
            ['letra' => 'N','entero' =>99,'decimal' => 9, 'significado' => ' Trastorno no especificado del sistema genitourinario consecutivo a procedimientos']
        ];
        foreach($dxAsociados as $dxAsociado){
            DxAsociado::insert($dxAsociado);
        }
    }
}
